language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  
env:
  - TEST_SUITE=Unit
  - TEST_SUITE=Fullstack
  
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TEST_SUITE=Static
  allow_failures:
    - php: 5.3
    - php: hhvm
    - env: TEST_SUITE=Static

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

install:
  - pecl install SPL_Types
  - curl -sS https://getcomposer.org/installer | php
  - chmod +x ./composer.phar
  - ./composer.phar --version
  - ./composer.phar install
  
script:
  - >
    sh -c "if [ '$TEST_SUITE' = 'Unit' ] || [ '$TEST_SUITE' = 'Fullstack' ]; then 
    ./vendor/bin/phpunit --coverage-clover=coverage.clover --testsuite=$TEST_SUITE;
    fi"
  - > 
    sh -c "if [ '$TEST_SUITE' = 'Static' ]; then
    ./vendor/bin/phpcs --standard=PSR2 ./src/;
    ./vendor/bin/phpcs --standard=PSR2 ./tests/MagentoHackathon;
    fi"
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    recipients:
      - olegkulik1985@gmail.com
    on_success: never
    on_failure: always
